### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by inakae** [paissaheavyindustries/Triggernometry#14] opened 2019-10-14 07:59 UTC
Hello,

I've some issues with the plugin since few days, i'll try to explain it as best as i can.

It happens randomly during any type of gameplay, but mostly in dungeons / raids, i'm hearing a weird sound from my headset, the sound drivers seems to be crashing (No more sounds at all on game / discord, but half of the time, i can still hear the trigger's TTS) and i'm lagging a lot (looks like i've 10 fps even tho' the game shows 100+).

I disabled HW acceleration and it doesn't seems to be crashing anymore (I need to try more). (I enabled it because some aura had some pink borders without it)
I'm using a 144hz g-sync monitor and all my drivers/plugins are up-to-date.
It looks like either a problem with HW acce, or with some drivers? Dunno if there's any way to debug this and provide logs.

**Comment by paissaheavyindustries** [comment] 2019-10-19 17:36
Duplicate of 13

**Closed as completed by paissaheavyindustries** 2019-10-19 17:36 UTC
